
KBUILD_EXTRA_SYMBOLS := /home/nitin/thesis/modules/my_char_dev/Module.symvers
KBUILD_EXTRA_SYMBOLS := /home/nitin/thesis/modules/my_char_dev_return/Module.symvers
obj-m += read_inode_list.o

KDIR := /lib/modules/`uname -r`/build

PWD := `pwd`

all:
	        make -C $(KDIR) M=$(PWD) modules

clean:
	        make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
