
KBUILD_EXTRA_SYMBOLS := /home/nitin/thesis/modules/Module.symvers

obj-m += user_process_call_test.o

KDIR := /lib/modules/`uname -r`/build

PWD := `pwd`

all:
	        make -C $(KDIR) M=$(PWD) modules

clean:
	        make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
